#!/bin/sh

# NOTE THIS WAS MADE FOR WINDOWS GITBASH.  YOUR MILEAGE MAY VARY.

#
# THE PATHS NEED TO BE CHANGED IF YOU RUN THIS, OBVIOUSLY.
#

CKAN="/d/SteamLibrary_2/steamapps/common/Kerbal Space Program/GameData/ckan.exe"
GITDIR="./"
MODFILENAME="modlist.md"
MODFILEPATH="${GITDIR}${MODFILENAME}"

echo "GENERATING NEW MOD LIST FILE"

# THIS IS A FRAGILE SCRIPT BASED ON LOOKING AT THE TEXT
# OUTPUT OF THE CKAN COMMAND.  IF CKAN CHANGES THEIR
# OUTPUT FORMAT, THIS SCRIPT WILL BREAK.

# Expected format:
#
#   stuff, script bypasses and ignores
#   A line containing the phrase "Installed Modules"
#   stuff, script bypasses and ignores until it hits...
#   an empty line
#   A List of Mods one per line:
#      Some of these lines have preceding "- ","+ ", or "A " strings
#      on the lefthand side, which have to do with how the mod got installed,
#      so the script strips and ignores those prefix strings if they exist.
#   <eof>

echo "### Dunbaratu's Mod list from CKAN" > ${MODFILEPATH}
echo "" >> ${MODFILEPATH}
echo "*This file was generated by the script \`\`${0}\`\`*<br/>" >> ${MODFILEPATH}
echo "*At timestamp (UTC time) \`\`"`date -u`"\`\`*" >> ${MODFILEPATH}
echo "" >> ${MODFILEPATH}
echo "#### LIST:" >> ${MODFILEPATH}
echo "" >> ${MODFILEPATH}
"$CKAN" list |\
    sed '0,/^Installed Modules/d' |\
    sed '0,/^ *$/d' |\
    sed '/^ *$/,$d' |\
    sed 's/^[+-A] \([^ ]*\).*$/* \1/g' |\
    sed '1,1s/^, //g' >> ${MODFILEPATH}

#
# Now the git commands to push the output file to git
#

echo "NEW MOD LIST: ${MODFILEPATH}"
echo -n "DO YOU WISH TO COMMIT AND PUSH IT UP? (y/n)? "
read yesno
if [ "$yesno" = "y" -o "$yesno" = "Y" ]
then
  echo "PUSHING"
  cd ${GITDIR}
  git commit -m "Autocommit by $0" ${MODFILENAME}
  git push origin master
  echo "DONE PUSHING"
else
  echo "NOT PUSHING"
fi
