#!/bin/sh

CKAN="/d/SteamLibrary_2/steamapps/common/Kerbal Space Program/GameData/ckan.exe"
GITDIR="./"
MODFILENAME="modlist.md"
MODFILEPATH="${GITDIR}${MODFILENAME}"

echo "GENERATING NEW MOD LIST FILE"

# List all mods, trimming the output to everything
# after a section like so:
#################
# Installed Modules:
# <blank line>
#################
# And then trimming everything after a blank line:

echo "### Dunbaratu's autogenerated kerbal mod list from CKAN" > ${MODFILEPATH}
echo "" >> ${MODFILEPATH}
echo -n "**This file was generated:** " >> ${MODFILEPATH}
echo "*(UTC TIME) "`date -u`"*" >> ${MODFILEPATH}
echo "" >> ${MODFILEPATH}
echo "#### LIST:" >> ${MODFILEPATH}
echo "" >> ${MODFILEPATH}
"$CKAN" list |\
    sed '0,/^Installed Modules/d' |\
    sed '0,/^ *$/d' |\
    sed '/^ *$/,$d' |\
    sed 's/^[+-A] \([^ ]*\).*$/* \1/g' |\
    sed '1,1s/^, //g' >> ${MODFILEPATH}

echo "NEW MOD LIST: ${MODFILEPATH}"
echo -n "DO YOU WISH TO COMMIT AND PUSH IT UP? (y/n)? "
read yesno
if [ "$yesno" = "y" -o "$yesno" = "Y" ]
then
  echo "PUSHING"
  cd ${GITDIR}
  git commit -m "Autocommit by $0" ${MODFILENAME}
  git push origin master
  echo "DONE PUSHING"
else
  echo "NOT PUSHING"
fi
