#!/bin/sh

# NOTE THIS WAS MADE FOR WINDOWS GITBASH.  YOUR MILEAGE MAY VARY.

#
# THE PATHS NEED TO BE CHANGED IF YOU RUN THIS, OBVIOUSLY.
#

CKAN="/d/SteamLibrary_2/steamapps/common/Kerbal Space Program/GameData/ckan.exe"
WHICHKSP="Steam with auto-updates" # the CKAN name for the install to use
STARTDIR="${PWD}"
STAGINGDIR="${STARTDIR}/html-staging/"
GHPAGESDIR="${STARTDIR}/html/"
MODFILENAME="modlist.html"
MODFILESTAGING="${STAGINGDIR}${MODFILENAME}"

echo "GENERATING NEW MOD LIST FILE"

cat > ${MODFILESTAGING} <<ENDMARK
<!doctype html>
<head>
  <title>Dunbaratu autogenerated KSP mod list</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body {font-family: sans-serif;}
  </style>
</head>
<body>
  <section>
    <h3>Dunbaratu autogenerated KSP mod list</h3>
    <p>
    The file you are viewing was generated at: <code> `date` (UTC)</code>
    </p>
    <p>
    The CKAN name for this instance of KSP is <code>"${WHICHKSP}"</code>.
    </p>
    <ul>
ENDMARK

# THIS IS A FRAGILE SCRIPT BASED ON LOOKING AT THE TEXT
# OUTPUT OF THE CKAN COMMAND.  IF CKAN CHANGES THEIR
# OUTPUT FORMAT, THIS SCRIPT WILL BREAK.

# Expected format:
#
#   stuff, script bypasses and ignores
#   A line containing the phrase "Installed Modules"
#   stuff, script bypasses and ignores until it hits...
#   an empty line
#   A List of Mods one per line:
#      Some of these lines have preceding "- ","+ ", or "A " strings
#      on the lefthand side, which have to do with how the mod got installed,
#      so the script strips and ignores those prefix strings if they exist.
#   <eof>

"$CKAN" ksp default "${WHICHKSP}"

"$CKAN" list |\
    sed '0,/^Installed Modules/d' |\
    sed '0,/^ *$/d' |\
    sed '/^ *$/,$d' |\
    sed 's/^[+-A] \([^ ]*\).*$/      <li>\1<\/li>/g' |\
    sed '1,1s/^, //g' >> ${MODFILESTAGING}

cat >> "${MODFILESTAGING}" << ENDMARK
    </ul>
  </section>
  <section>
    <h4>Where is the script</h4>
    <small>
      The script that automatically generates this list, called
      <code>${0}</code>, is located in the master branch of this
      git repository (not gh-pages).  (In a nutshell, when it
      runs it has CKAN print out the mod list, wraps it in some
      HTML markup, and pushes the resulting file to this repo's
      gh-pages branch so you can see it here.)
    </small>
  </section>
</body>
ENDMARK

#
# Now the git commands to push the output file to git
#

echo "NEW MOD LIST: ${MODFILESTAGING}"
echo -n "DO YOU WISH TO COMMIT AND PUSH IT UP? (y/n)? "
read yesno
if [ "$yesno" = "y" -o "$yesno" = "Y" ]
then
  echo "SWITCHING TO GH-PAGES"
  cd "${GHPAGESDIR}"
  echo "COPYING HTML OUTPUT TO GH-PAGES".
  cp "${MODFILESTAGING}" "${GHPAGESDIR}"
  echo "PUSHING"
  git add "${MODFILENAME}"
  git commit -m "Autocommit by $0" "${MODFILENAME}"
  git push origin gh-pages
  echo "DONE PUSHING"
  echo "SWITCHING TO MASTER"
  cd "${STARTDIR}"
  git checkout master
else
  echo "NOT PUSHING"
fi
